import { DEFAULT_FERRY, BAYS, VEHICLE_STATUS, PRIORITY_LEVELS, createQueueEntryDoc } from './constants';

export const INITIAL_MOCK_CROSSING = {
  id: 'crossing-42',
  ferryId: DEFAULT_FERRY.id,
  status: 'LOADING',
  activeMasterSessionId: null, // Will hold current master session tab ID
  createdAt: new Date().toISOString(),
  castOffAt: null,
  completedAt: null,
};

export const INITIAL_MOCK_QUEUE = [
  // Already loaded on deck (Crossing #42)
  createQueueEntryDoc({
    id: 'veh-18',
    checkInCode: 'FERRY-18TK',
    vehicleType: 'TRUCK',
    declaredWeight: 3400,
    verifiedWeight: 3400,
    hazardous: false,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.LOADED,
    bay: BAYS.LEFT,
    crossingId: 'crossing-42',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  }),
  createQueueEntryDoc({
    id: 'veh-19',
    checkInCode: 'FERRY-19VN',
    vehicleType: 'VAN',
    declaredWeight: 1700,
    verifiedWeight: 1700,
    hazardous: false,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.LOADED,
    bay: BAYS.CENTER,
    crossingId: 'crossing-42',
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  }),
  createQueueEntryDoc({
    id: 'veh-20',
    checkInCode: 'FERRY-20CR',
    vehicleType: 'CAR',
    declaredWeight: 2100,
    verifiedWeight: 2100,
    hazardous: false,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.LOADED,
    bay: BAYS.RIGHT,
    crossingId: 'crossing-42',
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  }),

  // Waiting in Queue
  createQueueEntryDoc({
    id: 'veh-21',
    checkInCode: 'FERRY-21AM',
    vehicleType: 'AMBULANCE',
    declaredWeight: 2600,
    verifiedWeight: null,
    hazardous: false,
    priority: PRIORITY_LEVELS.EMERGENCY,
    status: VEHICLE_STATUS.WAITING,
    bay: null,
    crossingId: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  }),
  createQueueEntryDoc({
    id: 'veh-22',
    checkInCode: 'FERRY-22TR',
    vehicleType: 'TRUCK',
    declaredWeight: 3200,
    verifiedWeight: 3200,
    hazardous: false,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.READY,
    bay: null,
    crossingId: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  }),
  createQueueEntryDoc({
    id: 'veh-23',
    checkInCode: 'FERRY-23VN',
    vehicleType: 'VAN',
    declaredWeight: 2100,
    verifiedWeight: null,
    hazardous: false,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.WAITING,
    bay: null,
    crossingId: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  }),
  createQueueEntryDoc({
    id: 'veh-24',
    checkInCode: 'FERRY-24CR',
    vehicleType: 'CAR',
    declaredWeight: 1500,
    verifiedWeight: null,
    hazardous: false,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.WAITING,
    bay: null,
    crossingId: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  }),
  createQueueEntryDoc({
    id: 'veh-25',
    checkInCode: 'FERRY-25HZ',
    vehicleType: 'TRUCK',
    declaredWeight: 2800,
    verifiedWeight: 3200,
    hazardous: true,
    priority: PRIORITY_LEVELS.NORMAL,
    status: VEHICLE_STATUS.WAITING,
    bay: null,
    crossingId: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  }),
];
